option(JULIA "Set this for enabling Julia BinaryBuilder mode" OFF)
option(OMP "Set this for using OpenMP" OFF)
option(OPT "Set this for using optimisation" OFF)
option(VALGRIND "Set this for enabling Valgrind for tests" OFF)
set(C_COMPILER gcc)
if (JULIA)
    set(SuiteSparse_DIR ${CMAKE_INSTALL_PREFIX})
    message("SuiteSparse_DIR is set to ${SuiteSparse_DIR}")
else()
    set(SuiteSparse_DIR /usr/lib/x86_64-linux-gnu/)
endif()